import {spawn} from 'node:child_process';
import http from 'node:http';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url));
await mkdir(path.join(root,'verification'),{recursive:true});
let httpMode=false,httpRequest=null,httpKey=null,httpResultOverrides={},httpTaskRequest=null,httpTaskKey=null,httpTaskPolls=0;
const server=http.createServer(async(req,res)=>{try{
 const url=new URL(req.url,'http://localhost');const json=body=>{res.writeHead(200,{'Content-Type':'application/json'});res.end(JSON.stringify(body))};
 if(httpMode&&url.pathname==='/config.js'){res.writeHead(200,{'Content-Type':'text/javascript'});res.end('window.LK_CONFIG=Object.freeze({mode:"http",baseUrl:"/api/v1",requestTimeoutMs:5000,pollIntervalMs:100,maxPollDurationMs:5000});');return}
 if(httpMode&&url.pathname.startsWith('/api/v1/')){const endpoint=url.pathname.slice('/api/v1'.length);
  if(endpoint==='/task-submissions'&&req.method==='POST'){let body='';for await(const chunk of req)body+=chunk;httpTaskRequest=JSON.parse(body);httpTaskKey=req.headers['idempotency-key'];const sample=JSON.parse(await readFile(path.join(root,'backend-package/examples/task-submission-accepted.json'),'utf8'));Object.assign(sample.data,{taskId:httpTaskRequest.taskId,taskVersion:httpTaskRequest.taskVersion,files:httpTaskRequest.files,status:'queued',verdict:null,feedback:null,pollAfterMs:300});json(sample);return}
  if(endpoint.startsWith('/task-submissions/')){httpTaskPolls++;const sample=JSON.parse(await readFile(path.join(root,'backend-package/examples/task-submission-accepted.json'),'utf8'));Object.assign(sample.data,{taskId:httpTaskRequest.taskId,taskVersion:httpTaskRequest.taskVersion,files:httpTaskRequest.files});json(sample);return}
  if(endpoint==='/submissions'&&req.method==='POST'){let body='';for await(const chunk of req)body+=chunk;httpRequest=JSON.parse(body);httpKey=req.headers['idempotency-key'];const sample=JSON.parse(await readFile(path.join(root,'backend-package/examples/submission-queued.json'),'utf8'));sample.data.lessonId=httpRequest.lessonId;sample.data.exerciseId=httpRequest.exerciseId;json(sample);return}
  if(endpoint==='/submissions'){json({data:[],meta:{schemaVersion:'1.0'}});return}
  if(endpoint.startsWith('/submissions/')){const sample=JSON.parse(await readFile(path.join(root,'backend-package/examples/submission-accepted.json'),'utf8'));sample.data.lessonId=httpRequest.lessonId;sample.data.exerciseId=httpRequest.exerciseId;sample.data.files=httpRequest.files;Object.assign(sample.data,httpResultOverrides);json(sample);return}
  const relative=endpoint==='/courses'?'courses/index':endpoint.slice(1);res.writeHead(200,{'Content-Type':'application/json'});res.end(await readFile(path.join(root,'backend-package/responses',relative+'.json')));return;
 }
 const filename=path.resolve(root,'.'+decodeURIComponent(url.pathname==='/'?'/index.html':url.pathname));if(!filename.startsWith(root+path.sep))throw new Error('Invalid path');const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.json':'application/json'};const data=await readFile(filename);res.writeHead(200,{'Content-Type':mime[path.extname(filename)]||'application/octet-stream','Cache-Control':'no-store'});res.end(data);
 }catch{res.writeHead(404);res.end('Not found')}});
await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(4173,'127.0.0.1',resolve)});
const browser=spawn('C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe',['--headless=new','--disable-gpu','--no-first-run','--no-default-browser-check','--remote-debugging-port=9337',`--user-data-dir=${path.join(root,'verification','browser-profile')}`,'about:blank'],{windowsHide:true,stdio:'ignore'});
const pause=ms=>new Promise(r=>setTimeout(r,ms));let socket;const assertions=[],errors=[];function check(value,label){assertions.push({label,pass:!!value});if(!value)throw new Error(label)}
try{
 let tabs;for(let i=0;i<40;i++){try{tabs=await(await fetch('http://127.0.0.1:9337/json',{signal:AbortSignal.timeout(500)})).json();break}catch{await pause(200)}}if(!tabs)throw new Error('Headless Edge did not start');
 socket=new WebSocket(tabs.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise((resolve,reject)=>{socket.onopen=resolve;socket.onerror=reject});let next=0;const pending=new Map();socket.onmessage=event=>{const m=JSON.parse(event.data);if(m.id){const p=pending.get(m.id);if(p){pending.delete(m.id);m.error?p.reject(new Error(JSON.stringify(m.error))):p.resolve(m.result)}}else if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.exception?.description||m.params.exceptionDetails.text)};
 const cdp=(method,params={})=>new Promise((resolve,reject)=>{const id=++next;const timer=setTimeout(()=>{pending.delete(id);reject(new Error('CDP timeout: '+method))},15000);pending.set(id,{resolve:v=>{clearTimeout(timer);resolve(v)},reject:e=>{clearTimeout(timer);reject(e)}});socket.send(JSON.stringify({id,method,params}))});
 const evaluate=async expression=>{if(expression.startsWith('(await '))expression='(async()=>('+expression+'))()';const r=await cdp('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw new Error(r.exceptionDetails.exception?.description||'Evaluation failed');return r.result.value};
 const waitFor=async(expression,label='Condition')=>{for(let i=0;i<80;i++){if(await evaluate(expression))return;await pause(80)}throw new Error('Timeout: '+label)};
 const click=selector=>evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`);
 const route=async(hash,ready='.reading-article')=>{await evaluate(`location.hash=${JSON.stringify(hash)}`);await pause(50);if(ready)await waitFor(`!!document.querySelector(${JSON.stringify(ready)})`,hash)};
 const navigate=async url=>{await evaluate('window.__verificationLeaving=true');await cdp('Page.navigate',{url});await waitFor('!window.__verificationLeaving && document.readyState === "complete"','new document')};
 const reload=async()=>{await evaluate('window.__verificationLeaving=true');await cdp('Page.reload',{ignoreCache:true});await waitFor('!window.__verificationLeaving && document.readyState === "complete"','reloaded document')};
 const input=(selector,value)=>evaluate(`{const e=document.querySelector(${JSON.stringify(selector)});e.value=${JSON.stringify(value)};e.dispatchEvent(new Event('input',{bubbles:true}));}`);
 const screenshot=async name=>{await pause(200);const r=await cdp('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});await writeFile(path.join(root,'verification',name+'.png'),Buffer.from(r.data,'base64'))};
 await cdp('Runtime.enable');await cdp('Page.enable');await cdp('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});await cdp('Page.navigate',{url:'http://127.0.0.1:4173/'});await waitFor(`typeof coursesReady!=='undefined'&&coursesReady`,'catalog bootstrap');await evaluate('localStorage.clear()');await reload();await waitFor(`typeof coursesReady!=='undefined'&&coursesReady`);
 check(await evaluate(`courses.length===11&&!courses.some(c=>c.id==='react')`),'11 courses; React removed');check(await evaluate(`document.documentElement.dataset.theme==='light'`),'Default light theme');await screenshot('desktop-light');
 await evaluate("courses.splice(0,courses.length,...courses.filter(c=>c.id==='go'));state.enrolled=['go'];render()");check(await evaluate("document.querySelector('#chart-title').textContent.includes('Go')&&document.querySelector('.continue-details b').textContent==='Go'&&document.querySelector('.continue-course a').getAttribute('href')==='#/lesson/go'"),'Home uses courses supplied by API');await evaluate('courses.splice(0);render()');check(await evaluate("document.querySelector('#main').textContent.includes('Каталог пока пуст')"),'Empty catalog home');await reload();await waitFor("typeof coursesReady!=='undefined'&&coursesReady");
 await route('#/courses','.catalog-grid');check(await evaluate(`document.querySelectorAll('.catalog-card').length===11`),'All course cards');await screenshot('catalog-v2');await input('#course-search','C#');check(await evaluate(`document.querySelectorAll('.catalog-card').length===1`),'Search C#');await input('#course-search','');
 await route('#/course/rust','.course-introduction');check(await evaluate(`document.querySelectorAll('.outline-lesson').length===60`),'Course outline has 60 lessons');await screenshot('course-outline');
 await route('#/lesson/python/python-01');check(await evaluate(`document.querySelectorAll('.reading-prose p').length>=10`),'Expanded beginner explanation');check(await evaluate(`document.querySelector('#lesson-code').value.includes('#')`),'Python editor scaffold');await screenshot('lesson-light');await click('[data-action="theme"]');await screenshot('lesson-dark');check(await evaluate(`getComputedStyle(document.body).color==='rgb(242, 243, 245)'`),'Dark text contrast');await click('[data-action="theme"]');
 await input('#lesson-code','print("Мой черновик")');await pause(350);await route('#/lesson/python/python-02');await route('#/lesson/python/python-01');check(await evaluate(`document.querySelector('#lesson-code').value==='print("Мой черновик")'`),'Per-lesson draft restored');await click('[data-action="lesson-mark-read"]');check(await evaluate(`state.lessonReads.includes('python-01')&&!state.completed.python?.includes('python-01')`),'Reading does not pass practice');
 await evaluate(`document.querySelector('#lesson-practice').scrollIntoView()`);await screenshot('editor-light');await click('[data-action="lesson-submit"]');await waitFor(`document.querySelector('#submission-result').textContent.includes('Проект ещё в разработке')`);check(await evaluate(`!state.completed.python?.includes('python-01')&&!LKApi.debug.getLog().some(x=>x.method==='POST')`),'Development submission neither sends nor passes');
 await click('[data-action="lesson-history-tab"]');check(await evaluate(`document.querySelectorAll('.history-attempt').length===0`),'No simulated attempts');
 await input('#lesson-code','print("Сохранено")');await pause(350);await reload();await waitFor(`!!document.querySelector('#lesson-code')`);check(await evaluate(`document.querySelector('#lesson-code').value==='print("Сохранено")'`),'Draft survives reload');
 for(const id of ['reverse','sum','palindrome','unique','fizzbuzz','binary']){await route('#/task/'+id,'#code-editor');await input('#code-editor','globalThis.__studentCodeRan = true; throw new Error("EXECUTED")');const before=await evaluate('state.xp');await click('[data-action="submit-task"]');check(await evaluate(`document.querySelector('#test-results').textContent.includes('Проект ещё в разработке')&&!globalThis.__studentCodeRan&&!document.querySelector('iframe')&&!state.solved.includes('`+id+`')`),'Task never executes '+id);check(await evaluate('state.xp')===before,'No local XP '+id)}
 await evaluate(`document.querySelector('#code-editor').dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',ctrlKey:true,bubbles:true}))`);check(await evaluate(`document.querySelector('#test-results').textContent.includes('Проект ещё в разработке')`),'Keyboard submission also disabled');
 await route('#/task/reverse','#code-editor');check(await evaluate(`document.querySelector('#code-editor').value.includes('__studentCodeRan')`),'Task draft restored');
 for(const id of ['python','js','algorithms','html','sql','ts','csharp','c','cpp','go','rust']){await route('#/lesson/'+id+'/'+id+'-01');check(await evaluate(`document.querySelector('#lesson-code')!==null`),'Beginner editor '+id);await route('#/lesson/'+id+'/'+id+'-60');check(await evaluate(`/[Пп]роект/.test(document.querySelector('.reading-article h1').textContent)`),'Final project '+id)}
 for(const id of ['python','js','algorithms','html','sql','ts','csharp','c','cpp','go','rust'])for(let n=1;n<=60;n++){const lessonId=id+'-'+String(n).padStart(2,'0');await route('#/lesson/'+id+'/'+lessonId);check(await evaluate("document.querySelector('.reading-article')!==null&&document.querySelector('#lesson-code')!==null&&location.hash.endsWith('/"+lessonId+"')"),'Render lesson '+lessonId)}
 check(await evaluate(`(await Promise.all(courses.map(async c=>{const detail=(await LKApi.getCourse(c.id)).data;return Promise.all(detail.modules.flatMap(m=>m.lessons).map(async l=>{const lesson=(await LKApi.getLesson(l.id)).data;return lesson.blocks.length>=10&&lesson.exercise.files.length>0}))}))).flat().every(Boolean)`),'All 660 lesson DTOs load through API');
 await route('#/lesson/sql/sql-01');check(await evaluate(`document.querySelectorAll('.fixture-scroll table').length===2`),'SQL fixture');for(const width of [1280,1024,768,390,360]){await cdp('Emulation.setDeviceMetricsOverride',{width,height:900,deviceScaleFactor:1,mobile:width<700});await pause(70);check(await evaluate('document.documentElement.scrollWidth<=innerWidth'),'Lesson fits '+width)}await evaluate('scrollTo(0,0)');await screenshot('lesson-mobile');await evaluate(`document.querySelector('#lesson-practice').scrollIntoView()`);await screenshot('editor-mobile');
 for(const page of ['courses','course/go','tasks','certificates','achievements','library','settings']){await route('#/'+page,page.startsWith('course/')?'.course-introduction':page==='courses'?'.catalog-grid':null);await pause(120);check(await evaluate('document.documentElement.scrollWidth<=innerWidth'),'Mobile route '+page)}
 await route('#/lesson/go/go-01');await click('[data-action="lesson-expand"]');check(await evaluate(`document.body.classList.contains('editor-expanded')`),'Editor expands');await route('#/home','.dashboard');check(await evaluate(`!document.body.classList.contains('editor-expanded')`),'Navigation cleans editor');await evaluate('LKApi.debug.failNext()');await route('#/lesson/c/c-01',null);await waitFor(`document.querySelector('.lesson-loading')?.textContent.includes('Не удалось')`);check(true,'Course fetch error');await click('[data-action="lesson-retry"]');await waitFor(`!!document.querySelector('#lesson-code')`);check(true,'Course retry');
 await route('#/lesson/python/python-60');check(await evaluate(`document.querySelectorAll('.file-tab').length===3`),'Project has source component and design files');await click('.file-tab:last-child');await input('#lesson-code','# Мой проектный разбор');await route('#/lesson/python/python-59');await route('#/lesson/python/python-60');await click('.file-tab:last-child');check(await evaluate(`document.querySelector('#lesson-code').value==='# Мой проектный разбор'`),'Project document draft restored');await click('[data-action="lesson-submit"]');check(await evaluate(`document.querySelector('#submission-result').textContent.includes('Проект ещё в разработке')`),'Advanced submission stays disabled locally');await screenshot('advanced-project-mobile');
 httpMode=true;await navigate('http://127.0.0.1:4173/?transport=http#/lesson/python/python-01');await waitFor(`window.LKApi?.mode==='http'&&!!document.querySelector('#lesson-code')`,'HTTP adapter');await input('#lesson-code','print("HTTP contract test")');await click('[data-action="lesson-submit"]');await waitFor(`document.querySelector('#submission-result').textContent.includes('Решение принято')`,'HTTP feedback');check(httpRequest?.lessonId==='python-01'&&httpRequest.lessonVersion===1&&httpRequest.exerciseVersion===1,'HTTP body matches contract');check(typeof httpKey==='string'&&httpKey.length>10,'Idempotency-Key HTTP header');check(await evaluate(`state.completed.python.includes('python-01')`),'Server acceptance updates progress');check(await evaluate('!window.LK_MOCK_BUNDLE'),'HTTP mode excludes fixture bundle');
 await route('#/lesson/python/python-60');await click('.file-tab:last-child');await input('#lesson-code','# Архитектура проекта');await click('[data-action="lesson-submit"]');await waitFor(`document.querySelector('#submission-result').textContent.includes('Решение принято')`);check(httpRequest?.files.length===3&&httpRequest.files[2].path==='design.md'&&httpRequest.files[2].code.includes('Архитектура'),'Project source and review evidence sent together');check(httpRequest?.runtimeProfileId==='python-engineering-v1','Engineering runtime profile sent');
 httpResultOverrides={exerciseVersion:999};await route('#/lesson/python/python-02');await input('#lesson-code','print("stale version")');await click('[data-action="lesson-submit"]');await waitFor(`document.querySelector('#submission-result').textContent.includes('Результат для другой версии задания')`);check(await evaluate(`!state.completed.python.includes('python-02')`),'Stale server acceptance does not complete current exercise');httpResultOverrides={};
 await route('#/task/reverse','#code-editor');await input('#code-editor','function reverseString(str) { return str; }');await click('[data-action="submit-task"]');await waitFor(`document.querySelector('#test-results').classList.contains('success')`);check(httpTaskRequest?.taskId==='reverse'&&httpTaskRequest.files[0].path==='solution.js'&&httpTaskRequest.files[0].code.includes('return str'),'Task code sent to HTTP backend');check(typeof httpTaskKey==='string'&&httpTaskKey.length>10,'Task idempotency header');check(httpTaskPolls>0,'Task result polled from server');check(await evaluate(`state.solved.includes('reverse')&&!globalThis.__studentCodeRan`),'Task completion comes from server only');
 httpMode=false;await navigate(new URL('./index.html',import.meta.url).href+'#/lesson/rust/rust-01');await waitFor(`!!document.querySelector('#lesson-code')`,'Direct file launch');check(await evaluate(`LKApi.mode==='mock'`),'Direct file mode');await input('#lesson-code','fn main() { println!("Hello"); }');await click('[data-action="lesson-submit"]');await waitFor(`document.querySelector('#submission-result').textContent.includes('Проект ещё в разработке')`);check(true,'Direct file submission');check(errors.length===0,'No browser runtime exceptions');
 await writeFile(path.join(root,'verification/results-v2.json'),JSON.stringify({assertions,errors},null,2));console.log(JSON.stringify({passed:assertions.length,errors},null,2));await cdp('Browser.close');
}catch(error){console.error(error);await writeFile(path.join(root,'verification/results-v2.json'),JSON.stringify({assertions,errors,failure:error.message},null,2));process.exitCode=1;}
finally{socket?.close();browser.kill();server.closeAllConnections();server.close()}
