// Public task descriptions, code is sent to the server as text
window.LK_TASKS = [
  {
    "id": "reverse",
    "title": "Обратная строка",
    "topic": "Строки",
    "level": "Лёгкая",
    "xp": 50,
    "fn": "reverseString",
    "args": "str",
    "description": "Верните новую строку, в которой символы исходной строки идут в обратном порядке. Исходную строку изменять не нужно.",
    "example": "reverseString(\"hello\") → \"olleh\"",
    "starter": "function reverseString(str) {\n  // Верните строку в обратном порядке\n  return str;\n}",
    "hint": "Преобразуйте строку в массив с помощью [...str], разверните массив методом reverse(), затем соедините символы через join('').",
    "version": 1,
    "language": "javascript",
    "runtimeProfileId": "javascript-functions-v1",
    "entryFile": "solution.js"
  },
  {
    "id": "sum",
    "title": "Сумма массива",
    "topic": "Массивы",
    "level": "Лёгкая",
    "xp": 50,
    "fn": "sumArray",
    "args": "numbers",
    "description": "Напишите функцию, которая возвращает сумму всех чисел массива. Для пустого массива результат должен быть равен 0.",
    "example": "sumArray([2, 4, 6]) → 12",
    "starter": "function sumArray(numbers) {\n  // Сложите все элементы массива\n  return 0;\n}",
    "hint": "Используйте reduce с начальным значением 0. На каждом шаге прибавляйте очередной элемент к аккумулятору.",
    "version": 1,
    "language": "javascript",
    "runtimeProfileId": "javascript-functions-v1",
    "entryFile": "solution.js"
  },
  {
    "id": "palindrome",
    "title": "Проверка палиндрома",
    "topic": "Строки",
    "level": "Средняя",
    "xp": 100,
    "fn": "isPalindrome",
    "args": "str",
    "description": "Проверьте, читается ли строка одинаково в обе стороны. Игнорируйте регистр букв и пробелы. Возвращайте true или false.",
    "example": "isPalindrome(\"А роза упала на лапу Азора\") → true",
    "starter": "function isPalindrome(str) {\n  // Нормализуйте строку и сравните с перевёрнутой\n  return false;\n}",
    "hint": "Приведите строку к нижнему регистру, удалите пробелы и сравните результат с перевёрнутой строкой.",
    "version": 1,
    "language": "javascript",
    "runtimeProfileId": "javascript-functions-v1",
    "entryFile": "solution.js"
  },
  {
    "id": "unique",
    "title": "Только уникальные",
    "topic": "Массивы",
    "level": "Лёгкая",
    "xp": 75,
    "fn": "unique",
    "args": "numbers",
    "description": "Удалите повторяющиеся числа из массива, сохранив порядок первого появления элементов. Верните новый массив.",
    "example": "unique([1, 2, 2, 3, 1]) → [1, 2, 3]",
    "starter": "function unique(numbers) {\n  return numbers;\n}",
    "hint": "Коллекция Set хранит только уникальные значения и сохраняет порядок вставки. Преобразуйте её обратно в массив.",
    "version": 1,
    "language": "javascript",
    "runtimeProfileId": "javascript-functions-v1",
    "entryFile": "solution.js"
  },
  {
    "id": "fizzbuzz",
    "title": "Классический FizzBuzz",
    "topic": "Логика",
    "level": "Средняя",
    "xp": 100,
    "fn": "fizzBuzz",
    "args": "n",
    "description": "Верните массив от 1 до n включительно. Замените числа, кратные 3, на \"Fizz\", кратные 5 — на \"Buzz\", кратные и 3, и 5 — на \"FizzBuzz\". Остальные элементы остаются числами.",
    "example": "fizzBuzz(5) → [1, 2, \"Fizz\", 4, \"Buzz\"]",
    "starter": "function fizzBuzz(n) {\n  const result = [];\n  // Добавьте элементы в result\n  return result;\n}",
    "hint": "Сначала проверьте кратность 15, затем 3 и 5. Остальные числа добавьте без изменений.",
    "version": 1,
    "language": "javascript",
    "runtimeProfileId": "javascript-functions-v1",
    "entryFile": "solution.js"
  },
  {
    "id": "binary",
    "title": "Бинарный поиск",
    "topic": "Алгоритмы",
    "level": "Сложная",
    "xp": 150,
    "fn": "binarySearch",
    "args": "arr, target",
    "description": "Найдите индекс target в отсортированном по возрастанию массиве. Если элемента нет, верните -1. Используйте бинарный поиск. Автоматические тесты проверяют результат; оцените сложность своего решения самостоятельно.",
    "example": "binarySearch([1, 3, 5, 7, 9], 7) → 3",
    "starter": "function binarySearch(arr, target) {\n  let left = 0;\n  let right = arr.length - 1;\n  // Сужайте диапазон поиска\n  return -1;\n}",
    "hint": "Сравните target со средним элементом. Если target меньше, передвиньте правую границу; иначе — левую.",
    "version": 1,
    "language": "javascript",
    "runtimeProfileId": "javascript-functions-v1",
    "entryFile": "solution.js"
  }
];
